name: geoengine
description: GeoEngine is a Dart library for geospatial analysis and geometry. It has precise distance calculations, coordinates conversions, geodetic processing, astronomy and GIS support.
version: 1.0.7
repository: https://github.com/gameticharles/geoengine

documentation: "https://github.com/gameticharles/geoengine/blob/main/doc/README.md"

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  advance_math: ^5.4.3
  dartframe: ^0.8.10
  mgrs_dart: ^2.0.0
  xml2json: ^6.2.7
  geoxml: ^2.6.2
  geojson_vi: ^2.2.5
  http: ^1.5.0
  kdtree: ^0.2.0
  r_tree: ^3.0.1
  latlng: ^2.0.7
  meta: ^1.17.0

dev_dependencies:
  benchmark_harness: ^2.3.1
  lints: ^6.0.0
  test: ^1.26.3

topics:
  - astronomy-ellipse-moon-sun
  - coordinate-conversions
  - geocoding-geolocation
  - earth-works
  - julian-date
